import './app/app.js';
import './app/app.routes.js';
import './app/common.scss';
import './app/home/home.routes.js';
import './app/home/home.controller.js';
import './app/home/home.scss';
import './app/services/s3.service.js';
import './app/components/navbar/navbar.controller.js';
import './app/components/navbar/navbar.scss';
